// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonGame = `-- name: AbandonGame :one
UPDATE games
SET status = 'abandoned',
    finished_at = NOW()
WHERE id = $1
RETURNING id, player_white_id, player_black_id, status, winner_id, end_reason, started_at, finished_at, created_at
`

func (q *Queries) AbandonGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, abandonGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlayerWhiteID,
		&i.PlayerBlackID,
		&i.Status,
		&i.WinnerID,
		&i.EndReason,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (player_white_id, player_black_id)
VALUES ($1, $2)
RETURNING id, player_white_id, player_black_id, status, winner_id, end_reason, started_at, finished_at, created_at
`

type CreateGameParams struct {
	PlayerWhiteID pgtype.UUID `json:"player_white_id"`
	PlayerBlackID pgtype.UUID `json:"player_black_id"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.PlayerWhiteID, arg.PlayerBlackID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlayerWhiteID,
		&i.PlayerBlackID,
		&i.Status,
		&i.WinnerID,
		&i.EndReason,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishGame = `-- name: FinishGame :one
UPDATE games
SET status     = 'finished',
    winner_id  = $2,
    end_reason = $3,
    finished_at = NOW()
WHERE id = $1
RETURNING id, player_white_id, player_black_id, status, winner_id, end_reason, started_at, finished_at, created_at
`

type FinishGameParams struct {
	ID        pgtype.UUID `json:"id"`
	WinnerID  *string     `json:"winner_id"`
	EndReason *string     `json:"end_reason"`
}

func (q *Queries) FinishGame(ctx context.Context, arg FinishGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, finishGame, arg.ID, arg.WinnerID, arg.EndReason)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlayerWhiteID,
		&i.PlayerBlackID,
		&i.Status,
		&i.WinnerID,
		&i.EndReason,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, player_white_id, player_black_id, status, winner_id, end_reason, started_at, finished_at, created_at FROM games
WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlayerWhiteID,
		&i.PlayerBlackID,
		&i.Status,
		&i.WinnerID,
		&i.EndReason,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGamesByUserID = `-- name: GetGamesByUserID :many
SELECT id, player_white_id, player_black_id, status, winner_id, end_reason, started_at, finished_at, created_at FROM games
WHERE player_white_id = $1 OR player_black_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetGamesByUserIDParams struct {
	PlayerWhiteID pgtype.UUID `json:"player_white_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) GetGamesByUserID(ctx context.Context, arg GetGamesByUserIDParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGamesByUserID, arg.PlayerWhiteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.PlayerWhiteID,
			&i.PlayerBlackID,
			&i.Status,
			&i.WinnerID,
			&i.EndReason,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startGame = `-- name: StartGame :one
UPDATE games
SET status = 'ongoing',
    started_at = NOW()
WHERE id = $1
RETURNING id, player_white_id, player_black_id, status, winner_id, end_reason, started_at, finished_at, created_at
`

func (q *Queries) StartGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, startGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlayerWhiteID,
		&i.PlayerBlackID,
		&i.Status,
		&i.WinnerID,
		&i.EndReason,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
