// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EndReason string

const (
	EndReasonCheckmate     EndReason = "checkmate"
	EndReasonResign        EndReason = "resign"
	EndReasonTimeout       EndReason = "timeout"
	EndReasonDrawAgreement EndReason = "draw_agreement"
	EndReasonStalemate     EndReason = "stalemate"
)

func (e *EndReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndReason(s)
	case string:
		*e = EndReason(s)
	default:
		return fmt.Errorf("unsupported scan type for EndReason: %T", src)
	}
	return nil
}

type NullEndReason struct {
	EndReason EndReason `json:"end_reason"`
	Valid     bool      `json:"valid"` // Valid is true if EndReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndReason) Scan(value interface{}) error {
	if value == nil {
		ns.EndReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndReason), nil
}

type GameStatus string

const (
	GameStatusWaiting   GameStatus = "waiting"
	GameStatusOngoing   GameStatus = "ongoing"
	GameStatusFinished  GameStatus = "finished"
	GameStatusAbandoned GameStatus = "abandoned"
)

func (e *GameStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameStatus(s)
	case string:
		*e = GameStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GameStatus: %T", src)
	}
	return nil
}

type NullGameStatus struct {
	GameStatus GameStatus `json:"game_status"`
	Valid      bool       `json:"valid"` // Valid is true if GameStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GameStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameStatus), nil
}

type Game struct {
	ID            pgtype.UUID        `json:"id"`
	PlayerWhiteID pgtype.UUID        `json:"player_white_id"`
	PlayerBlackID pgtype.UUID        `json:"player_black_id"`
	Status        GameStatus         `json:"status"`
	WinnerID      *string            `json:"winner_id"`
	EndReason     *string            `json:"end_reason"`
	StartedAt     *time.Time         `json:"started_at"`
	FinishedAt    *time.Time         `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Move struct {
	ID         pgtype.UUID        `json:"id"`
	GameID     pgtype.UUID        `json:"game_id"`
	PlayerID   pgtype.UUID        `json:"player_id"`
	MoveNumber int32              `json:"move_number"`
	FromX      int16              `json:"from_x"`
	FromY      int16              `json:"from_y"`
	ToX        int16              `json:"to_x"`
	ToY        int16              `json:"to_y"`
	Piece      string             `json:"piece"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	EmailVerified   bool               `json:"email_verified"`
	EmailVerifiedAt *time.Time         `json:"email_verified_at"`
	Password        string             `json:"password"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
