// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moves.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMove = `-- name: CreateMove :one
INSERT INTO moves (game_id, player_id, move_number, from_x, from_y, to_x, to_y, piece)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, game_id, player_id, move_number, from_x, from_y, to_x, to_y, piece, created_at
`

type CreateMoveParams struct {
	GameID     pgtype.UUID `json:"game_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
	MoveNumber int32       `json:"move_number"`
	FromX      int16       `json:"from_x"`
	FromY      int16       `json:"from_y"`
	ToX        int16       `json:"to_x"`
	ToY        int16       `json:"to_y"`
	Piece      string      `json:"piece"`
}

func (q *Queries) CreateMove(ctx context.Context, arg CreateMoveParams) (Move, error) {
	row := q.db.QueryRow(ctx, createMove,
		arg.GameID,
		arg.PlayerID,
		arg.MoveNumber,
		arg.FromX,
		arg.FromY,
		arg.ToX,
		arg.ToY,
		arg.Piece,
	)
	var i Move
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.MoveNumber,
		&i.FromX,
		&i.FromY,
		&i.ToX,
		&i.ToY,
		&i.Piece,
		&i.CreatedAt,
	)
	return i, err
}

const getLastMoveByGameID = `-- name: GetLastMoveByGameID :one
SELECT id, game_id, player_id, move_number, from_x, from_y, to_x, to_y, piece, created_at FROM moves
WHERE game_id = $1
ORDER BY move_number DESC
LIMIT 1
`

func (q *Queries) GetLastMoveByGameID(ctx context.Context, gameID pgtype.UUID) (Move, error) {
	row := q.db.QueryRow(ctx, getLastMoveByGameID, gameID)
	var i Move
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.MoveNumber,
		&i.FromX,
		&i.FromY,
		&i.ToX,
		&i.ToY,
		&i.Piece,
		&i.CreatedAt,
	)
	return i, err
}

const getMovesByGameID = `-- name: GetMovesByGameID :many
SELECT id, game_id, player_id, move_number, from_x, from_y, to_x, to_y, piece, created_at FROM moves
WHERE game_id = $1
ORDER BY move_number ASC
`

func (q *Queries) GetMovesByGameID(ctx context.Context, gameID pgtype.UUID) ([]Move, error) {
	rows, err := q.db.Query(ctx, getMovesByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Move
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.MoveNumber,
			&i.FromX,
			&i.FromY,
			&i.ToX,
			&i.ToY,
			&i.Piece,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
