// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, username, email, password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, first_name, last_name, username, email, email_verified, email_verified_at, password, created_at
`

type CreateUserParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = $1
) AS EXISTS
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, username, email, email_verified, email_verified_at, password, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, username, email, email_verified, email_verified_at, password, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
select id, username, password from users
where email = $1 or username = $1
limit 1
`

type GetUserByLoginRow struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Password string      `json:"password"`
}

func (q *Queries) GetUserByLogin(ctx context.Context, email string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, email)
	var i GetUserByLoginRow
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, first_name, last_name, username, email, email_verified, email_verified_at, password, created_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COUNT(*)                                                    AS total_games,
    COUNT(*) FILTER (WHERE winner_id = $1)                     AS wins,
    COUNT(*) FILTER (WHERE winner_id != $1 AND winner_id IS NOT NULL) AS losses,
    COUNT(*) FILTER (WHERE winner_id IS NULL AND status = 'finished') AS draws
FROM games
WHERE player_white_id = $1 OR player_black_id = $1
`

type GetUserStatsRow struct {
	TotalGames int64 `json:"total_games"`
	Wins       int64 `json:"wins"`
	Losses     int64 `json:"losses"`
	Draws      int64 `json:"draws"`
}

func (q *Queries) GetUserStats(ctx context.Context, winnerID *string) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, winnerID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.TotalGames,
		&i.Wins,
		&i.Losses,
		&i.Draws,
	)
	return i, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE username = $1
) AS exists
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyEmail = `-- name: VerifyEmail :one
UPDATE users
SET email_verified = TRUE,
    email_verified_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, username, email, email_verified, email_verified_at, password, created_at
`

func (q *Queries) VerifyEmail(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyEmail, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
